### ISSUE TITLE
Upgraded to latest version and now get YSOD 'GetEnqueuedJobIds' does not have an implementation?

### ISSUE THREAD

**Issue by YodasMyDad** [HangfireIO/Hangfire.Azure.ServiceBusQueue#11]
I have been using this for some time and it's been great. I thought I would upgrade to the latest version, I checked the docs and all seems the same in regards to setup. This is what I have (Which has been working).

```c#
var sqlStorage = new SqlServerStorage("umbracoDbDSN");
const string connectionString = "SB_Connnection_String";
sqlStorage.UseServiceBusQueues(new ServiceBusQueueOptions
{
	ConnectionString = connectionString,
	QueuePrefix = $"{website.SiteAlias}-{Environment.MachineName}",
	Queues = new[] {EnqueuedState.DefaultQueue}
});
GlobalConfiguration.Configuration.UseStorage(sqlStorage);
var options = new BackgroundJobServerOptions {WorkerCount = 6};
e.AppBuilder.UseHangfireServer(options);
```

Since I upgraded to latest version of this package AND latest version of Hangfire. I am getting this error.

> *Method 'GetEnqueuedJobIds' in type 'Hangfire.Azure.ServiceBusQueue.ServiceBusQueueMonitoringApi' from assembly 'Hangfire.Azure.ServiceBusQueue, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.*

```c#
[TypeLoadException: Method 'GetEnqueuedJobIds' in type 'Hangfire.Azure.ServiceBusQueue.ServiceBusQueueMonitoringApi' from assembly 'Hangfire.Azure.ServiceBusQueue, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.]
   Hangfire.Azure.ServiceBusQueue.ServiceBusQueueJobQueueProvider..ctor(ServiceBusQueueOptions options) +0
   Hangfire.Azure.ServiceBusQueue.ServiceBusQueueSqlServerStorageExtensions.UseServiceBusQueues(SqlServerStorage storage, ServiceBusQueueOptions options) +56
   FRF.Web.UmbracoApplicationEventHandler.UmbracoDefaultOwinStartupMiddlewareConfigured(Object sender, OwinMiddlewareConfiguredEventArgs e) in C:\**\UmbracoApplicationEventHandler.cs:185
   Umbraco.Web.UmbracoDefaultOwinStartup.OnMiddlewareConfigured(OwinMiddlewareConfiguredEventArgs args) +47
   Umbraco.Web.UmbracoDefaultOwinStartup.ConfigureMiddleware(IAppBuilder app) +70
```

Line 185 in the app start class is this

```
sqlStorage.UseServiceBusQueues(new ServiceBusQueueOptions
```

Slightly confused what the issue is?

**Comment by odinserj** [comment]
Thanks for reporting this. I've just added https://github.com/HangfireIO/Hangfire.Azure.ServiceBusQueue/pull/12 PR to handle this issue.

**Comment by odinserj** [comment]
@barclayadam released the fix as a part of version 4.0.0 that's already available on NuGet – https://www.nuget.org/packages/Hangfire.Azure.ServiceBusQueue/. Closing the issue.

**Comment by YodasMyDad** [comment]
Fantastic. Thanks

**Comment by lukaszjakubczak** [comment]
I have similar issue with version 4.1.0


```
System.TypeLoadException: Method 'Enqueue' in type 'Hangfire.Azure.ServiceBusQueue.ServiceBusQueueJobQueue' from assembly 'Hangfire.Azure.ServiceBusQueue, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at Hangfire.Azure.ServiceBusQueue.ServiceBusQueueJobQueueProvider..ctor(ServiceBusQueueOptions options)
   at Hangfire.Azure.ServiceBusQueue.ServiceBusQueueSqlServerStorageExtensions.UseServiceBusQueues(SqlServerStorage storage, ServiceBusQueueOptions options)
   at AdminHangfireService.Startup.<ConfigureServices>b__2_1(IGlobalConfiguration config) in C:\repos\Admin\AdminHangfireService\Startup.cs:line 30
   at Hangfire.HangfireServiceCollectionExtensions.<>c__DisplayClass1_0.<AddHangfire>b__7(IServiceProvider serviceProvider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Hangfire.HangfireServiceCollectionExtensions.ThrowIfNotConfigured(IServiceProvider serviceProvider)
   at Hangfire.HangfireApplicationBuilderExtensions.UseHangfireServer(IApplicationBuilder app, BackgroundJobServerOptions options, IEnumerable`1 additionalProcesses, JobStorage storage)
   at AdminHangfireService.Startup.Configure(IApplicationBuilder app) in C:\repos\Admin\AdminHangfireService\Startup.cs:line 50
```

**Comment by skielo** [comment]
Hi there, running into the same issue with version 4.1.0

`Method 'Enqueue' in type 'Hangfire.Azure.ServiceBusQueue.ServiceBusQueueJobQueue' from assembly 'Hangfire.Azure.ServiceBusQueue, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.`

Does anybody get around this issue?
